services:
  client:
    build:
      context: ../client
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://localhost:8080/api
    container_name: react-app
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api
    ports:
      - "3000:80"
    networks:
      - spring-network
    depends_on:
      - app

networks:
  spring-network:
    driver: bridge
